export enum SocketEvent {
  INVITE_USER,
  SEND_MESSAGE,
  TYPING,
  STOP_TYPING,
  READ_MESSAGE,
  SEND_FILE_METADATA,
  SEND_FILE_START,
  SEND_FILE_BUFFER,
  JOIN_VIDEO_CALL,
  RETURN_SIGNAL,
  STOP_VIDEO_CALL
}