export enum SocketEmitter {
  NEW_INVITATION,
  RECEIVE_MESSAGE,
  TYPING,
  TYPING_END,
  MESSAGE_READ,
  USER_OFFLINE,
  RECEIVE_FILE_METADATA,
  FILE_TRANSFER,
  VIDEO_CALL_JOIN,
  RECEIVE_SIGNAL,
  VIDEO_CALL_END
}